sms_send:
  comPort: 17
  imsi: 460016731650621
  iccid: 98681091081188857476
  rcvNum: 18616739315
  sendNum: 1069033347723
  type: 79

date_fmt: yyyy-MM-dd hh:mm:ss

msaccess:
  sms: c:/fengrui/Data/SMS.mdb
  otInfo: c:/fengrui/Data/OtInfo.mdb
  devInfo: c:/fengrui/Data/DEVINFO.mdb